# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_money', models.IntegerField(default=0, verbose_name='\u041f\u043e\u0442\u0440\u0430\u0447\u0435\u043d\u043d\u044b\u0435 \u0434\u0435\u043d\u044c\u0433\u0438')),
                ('earned_money', models.IntegerField(default=0, verbose_name='\u0417\u0430\u0440\u0430\u0431\u043e\u0442\u0430\u043d\u043d\u044b\u0435 \u0434\u0435\u043d\u044c\u0433\u0438')),
                ('sold_all', models.IntegerField(default=0, verbose_name='\u041f\u0440\u043e\u0434\u0430\u043d\u043e \u0432\u0441\u0435\u0433\u043e')),
            ],
            options={
                'verbose_name': '\u043e\u0441\u043d\u043e\u0432\u043d\u0430\u044f \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f',
                'verbose_name_plural': '\u041e\u0441\u043d\u043e\u0432\u043d\u0430\u044f \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f',
            },
        ),
    ]
