# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20160828_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u0424\u0418\u041e')),
                ('phone', models.CharField(help_text='\u041c\u044b \u043f\u043e\u0437\u0432\u043e\u043d\u0438\u043c \u0432\u0430\u043c \u0434\u043b\u044f \u0443\u0442\u043e\u0447\u043d\u0435\u043d\u0438\u044f \u0437\u0430\u043a\u0430\u0437\u0430.', max_length=11, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
                ('email', models.CharField(blank=True, help_text='\u041d\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e, \u043d\u043e \u043c\u044b \u0442\u0443\u0434\u0430 \u043f\u0440\u0438\u0448\u043b\u0435\u043c \u0434\u0430\u043d\u043d\u044b\u0435 \u043e \u0437\u0430\u043a\u0430\u0437\u0435.', max_length=32, null=True, verbose_name='Email')),
                ('isDelivery', models.BooleanField(default=False, help_text='\u041d\u0443\u0436\u043d\u0430 \u043b\u0438 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0430 ?', verbose_name='\u041d\u0443\u0436\u043d\u0430 \u043b\u0438 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0430')),
                ('address', models.CharField(blank=True, help_text='\u0423\u043a\u0430\u0436\u0438\u0442\u0435 \u0430\u0434\u0440\u0435\u0441, \u0434\u043b\u044f \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438', max_length=128, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0444\u043e\u0440\u043c\u043b\u0435\u043d\u0438\u044f')),
                ('isAgreed', models.BooleanField(verbose_name='\u0421\u043e\u0433\u043b\u0430\u0441\u043e\u0432\u0430\u043d\u043e')),
                ('isPaid', models.BooleanField(verbose_name='\u041e\u043f\u043b\u0430\u0447\u0435\u043d\u043e')),
                ('isDelivered', models.BooleanField(verbose_name='\u0414\u043e\u0441\u0442\u0430\u0432\u043b\u0435\u043d\u043e')),
            ],
            options={
                'verbose_name': '\u043f\u0440\u043e\u0434\u0443\u043a\u0442\u044b \u0432 \u043a\u043e\u0440\u0437\u0438\u043d\u0435',
                'verbose_name_plural': '\u041f\u0440\u043e\u0434\u0443\u043a\u0442\u044b \u0432 \u043a\u043e\u0440\u0437\u0438\u043d\u0435',
            },
        ),
    ]
