# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '\u0437\u0430\u043a\u0430\u0437\u044b', 'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u044b'},
        ),
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', '\u041d\u0430\u043b\u0438\u0447\u043d\u044b\u043c\u0438'), ('Internet', '\u042d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u044b\u043c\u0438')], default=0, help_text='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0441\u043f\u043e\u0441\u043e\u0431 \u043e\u043f\u043b\u0430\u0442\u044b', max_length=30, verbose_name='\u0421\u043f\u043e\u0441\u043e\u0431 \u043e\u043f\u043b\u0430\u0442\u044b'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0, editable=False, verbose_name='\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c'),
            preserve_default=False,
        ),
    ]
