# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20160828_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='secret',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
