# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='catalog.Product', verbose_name='\u041f\u0440\u043e\u0434\u0443\u043a\u0442'),
        ),
    ]
